version: '3'

services:
  herold_bot:
    container_name: herold_bot
    image: h0d0user/herold_bot:latest
    restart: always
    networks:
      - herold_net
    environment:
      - API_ID=YOURAPIID
      - API_HASH=YOURAPIHASH
      - SESSION=YOURSESSION
    volumes:
      - "/root/herold_bot/herold_database.db:/opt/herold_database.db"
      - "/root/herold_bot/congrats_file.txt:/opt/congrats_file.txt"
      - "/root/herold_bot/JustTalk.session:/opt/JustTalk.session"

volumes:
  herold_bot:

networks:
  herold_net: