version: '3'

services:
  herold_bot:
    container_name: herold_bot
    image: h0d0user/herold_bot:latest
    restart: always
    network_mode: host
    environment:
      - API_ID=YOURAPIID
      - API_HASH=YOURAPIHASH
      - SESSION=YOURSESSION
    volumes:
      - "/root/friends_ids_list.txt:/friends_ids_list.txt"
      - "/root/friend_response.txt:/friend_response.txt"
      - "/root/familiar_ids_list.txt:/familiar_ids_list.txt"
      - "/root/familiar_response.txt:/familiar_response.txt"
      - "/root/hr_response.txt:/hr_response.txt"
      - "/root/JustTalk.session:/JustTalk.session"
volumes:
  herold_bot: