version: '3'

services:
  herold_bot:
    container_name: herold_bot
    image: h0d0user/herold_bot:latest
    restart: always
    network_mode: host
    environment:
      - API_ID=YOURAPIID
      - API_HASH=YOURAPIHASH
      - SESSION=YOURSESSION
    volumes:
      - "/root/herold_bot/circulation_ids_list.txt:/opt/circulation_ids_list.txt"
      - "/root/herold_bot/circulation_response.txt:/opt/circulation_response.txt"
      - "/root/herold_bot/new_year_patterns.txt:/opt/new_year_patterns.txt"
      - "/root/herold_bot/JustTalk.session:/opt/JustTalk.session"
volumes:
  herold_bot: