version: '3'

services:
  herold_bot:
    container_name: herold_bot
    image: h0d0user/herold_bot:latest
    restart: always
    network_mode: host
    environment:
      - API_ID=YOURAPIID
      - API_HASH=YOURAPIHASH
      - SESSION=YOURSESSION
      - DEBUG_ENABLED=True
    volumes:
      - /opt/:/root/herold_bot/friends_ids_list.txt
      - /opt/:/root/herold_bot/banished_ids_list.txt
      - /opt/:/root/herold_bot/friend_response.txt
      - /opt/:/root/herold_bot/banished_response.txt
      - /opt/:/root/herold_bot/JustTalk.session
volumes:
  herold_bot: